[pytest]

addopts = -s -v --html=reports/report.html

markers =
    smoke: Smoke test cases
    sanity: Sanity test cases
    regression: Regression suite
    ui: UI automation tests
    api: API automation tests
    login: Login related tests